### ISSUE TITLE
"Standings" covered part of the video

### ISSUE THREAD

**Issue by Qiki** [GingerBear/nba-daily#35]
When started played the video, the "Standings" covered part of the video on the desktop site.  
:eyes: :smiley: :kissing: 

![screen shot 2015-12-14 at 2 29 05 pm](https://cloud.githubusercontent.com/assets/2540791/11791471/3582f2ac-a26f-11e5-8c7c-bbce743b7789.png)

**Comment by GingerBear** [comment]
ah, good find! 
@Marco1989 or @zhangxiangyu7, do either of you guys want to fix this?

**Comment by GingerBear** [comment]
fixed in https://github.com/GingerBear/nba-daily/pull/41
