### ISSUE TITLE
new version plan

### ISSUE THREAD

**Issue by GingerBear** [GingerBear/nba-daily#43]
### requirement: 
all about daily, anything i want to know today when I open the app
- today's games
  - for ended games (link to nba/espn/hupu game detail page )
    - start datetime
    - video highlights
    - stats highlights
  - for not ended games (link to nba/espn/hupu game detail page )
    - show still playing 
  - highlight interested team's game
  - top 10 plays of the day
- tomorrow's games
  - datetime
  - highlight interested team's game

### tech detail
use offline update instead of realtime scape 
- use github page to serve react app 
- use a cronjob to collect data every 1 hour and drop the json to a public storage
  - s3/dropbox/google drive as long as it allow cross site access

**Comment by Qiki** [comment]
@GingerBear i approved this!

**Comment by GingerBear** [comment]
@Qiki 😆

**Comment by Qiki** [comment]
@GingerBear 🐙

**Comment by GingerBear** [comment]
this is working
`fetch('https://dl.dropboxusercontent.com/s/cp0v71ykk8zcp5j/data.json')`

**Comment by GingerBear** [comment]
`fetch('https://dl.dropboxusercontent.com/s/zrugpv5u7z203xo/category.json')`

**Comment by GingerBear** [comment]
`fetch('https://dl.dropboxusercontent.com/s/jsxcz9u47ne9i0q/data_20161106.json')`
