### ISSUE TITLE
Show the most handsome NBA players

### ISSUE THREAD

**Issue by Qiki** [GingerBear/nba-daily#9]
Show the most handsome NBA players' personal data and cute images.
For example, Stephen Curry
![screen shot 2015-02-19 at 2 40 49 pm](https://cloud.githubusercontent.com/assets/2540791/6274397/529ff782-b845-11e4-8ce7-2820bf50376d.png)

**Comment by GingerBear** [comment]
make a pr by yourself

**Comment by Qiki** [comment]
:confused: i don't know how to do that!! you need to teach me!  :eyes: :no_mouth:

**Comment by GingerBear** [comment]
@Qiki

**Comment by GingerBear** [comment]
@Qiki

**Comment by GingerBear** [comment]
这这这！怎么还在这儿啊？

**Comment by Qiki** [comment]
@GingerBear :eyes:  what is the problem neil?

**Comment by Qiki** [comment]
@GingerBear  this issue is never solved.

**Comment by GingerBear** [comment]
@Qiki dududu! 你准备啥时候solve啊？

**Comment by Qiki** [comment]
@GingerBear look at you! neil! the comment from Feb 19 "make a pr by yourself",  啧啧啧，what a not nice guy! :bomb:  哼

**Comment by GingerBear** [comment]
dup https://github.com/GingerBear/nba-daily/issues/39
